

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */


public class Problem_2 {
	public static long sumEvenFibonacci() {
		int b = 1;
		int c = 2, d;
		long sum = 0;
		while(c < 4000000) {
		    sum += c;
		    d = b+(c<<0x01);
		    c = d+b+c;
		    b = d;
		}
		return sum;
	}

	public static void main(String[] args) {
		System.out.println(sumEvenFibonacci());
		
	}

}
